spring:
  data:
    mongodb:
  #    host: ${MONGO_HOST}
    rest:
      detection-strategy: annotated
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
        
    