spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
#       host: 192.168.99.100
    rest:
      detection-strategy: annotated
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: true
#server:
#  servlet:
#    contextPath: /api