steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fiddlerProcessor', '.']
images: ['gcr.io/$PROJECT_ID/fiddlerProcessor']